### ISSUE TITLE
[BUG]   Wrapping doesn't work with rotate in charts

### ISSUE THREAD

**Issue by SilchenkoEG** [gitbrent/PptxGenJS#1023]
Hello!
### Observed Behavior
If we change rotation, wrapping will not work. I use this prop 'catAxisLabelRotate'.

Type: Bug
Library Version: 3.8.0
Powerpoint Version: 365
Framework used: ReactJS

Thank you!

<img width="843" alt="no_wrap" src="https://user-images.githubusercontent.com/37275045/140415253-4257c512-b541-4bb5-83cb-c7f2f1f0e163.png">
<img width="821" alt="wrap" src="https://user-images.githubusercontent.com/37275045/140415256-6a02fbf9-9858-4ad1-bf22-0536ab38780b.png">

**Comment by gitbrent** [comment]
@SilchenkoEG - please provide the code you're using

**Comment by ReimaFrgos** [comment]
@SilchenkoEG This is expected behaviour of PowerPoint if you are using `catAxisLabelRotate`.  Wrapping text only applies if the rotation is set to 0. You can replicate this behaviour in PowerPoint, with a standard chart generated directly within PowerPoint. 

Your first image fails because rotation is not 0.
Your second image works because rotation is 0.

@gitbrent not an issue. Standard PowerPoint behaviour.
