### ISSUE TITLE
how to add non-breaking space?

### ISSUE THREAD

**Issue by alexanchek** [gitbrent/PptxGenJS#1058]
Is it possible to add non-breaking space into a presentation? I made the presentation with pptxgens, and it looks awesome. However, I get some breaking spaces with  positive or negative values like +5.05% or -35.45%. 
They look like this:
.......-
35.56%

**Comment by BistroStu** [comment]
This is Powerpoint behaviour, not pptxgenjs. There is no space between the hyphen and the number, so a non-breaking space will not help, the problem is Powerpoint breaks lines after hyphens in order to fit content into a smaller space. Try allowing more space or use a minus character − (Unicode U+2212) instead of a hyphen.

**Comment by gitbrent** [comment]
Thanks @BistroStu
