### ISSUE TITLE
Space in textbox 

### ISSUE THREAD

**Issue by matt88120** [gitbrent/PptxGenJS#1067]
Hi there,

i have an issue since i have updated library. All my text elements display a inset padding int Powerpoint. 
Margin & Inset are set to 0 in options. 

In PPTX, i have a 4pt text insertion into textbox. 

Any idea ?

![Capture d’écran 2022-02-15 à 16 52 24](https://user-images.githubusercontent.com/1491751/154098668-0cf870d4-b4a5-46d5-b709-40f9a7cf836a.png)
<img width="138" alt="Capture d’écran 2022-02-15 à 16 53 06" src="https://user-images.githubusercontent.com/1491751/154098680-bb8220ae-4fe5-4284-bed3-2e5fcd925b21.png">

**Comment by gitbrent** [comment]
What you're showing may be the `lineSpacing` or some other factor.

A more basic text object shows zero margin. Notice the highlighted selection here touching the top. 

PowerPoint will leave what you're referring to as space due to line height.

```javascript
let pptx = new PptxGenJS();
let slide = pptx.addSlide();

slide.addText(
	[
		{ text: "Textbox", breakLine: true },
		{ text: "(margin:0)", options: { fontSize: 12 } },
	],
	{ x: 6.5, y: 2, w: 3.0, h: 1.0, color: "FFFFFF", fill: { color: "FF0000" }, margin: 0 }
);

pptx.writeFile({ fileName: "PptxGenJS-Sandbox.pptx" });
```
![Screen Shot 2022-02-19 at 14 11 23](https://user-images.githubusercontent.com/7218970/154817464-ce0c14cf-f12b-4d25-a874-34c61808f034.png)

**Comment by matt88120** [comment]
Thanks. I understand that for top and bottom space. But it doesn't explain left and right padding in textbox.
