### ISSUE TITLE
Used below code snippet but still facing the issue. Please help me in resolving this issue

### ISSUE THREAD

**Issue by abhishekpani** [gitbrent/PptxGenJS#1087]
Follow up from https://github.com/gitbrent/PptxGenJS/issues/1084

Used below code snippet but still facing the issue. Please help me in resolving this issue

rows.push([{
text: "Line 1\nLine 2\nLine 3",
options: { color: "0088cc", bullet: { type: "number" } }
}]);

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/81961718/160354239-795ccbf5-b944-45aa-b410-529eac0b4964.png">

_Originally posted by @abhishekpani in https://github.com/gitbrent/PptxGenJS/issues/1084#issuecomment-1080291481_

**Comment by willsgh** [comment]
Your code snippet should be

rows.push({ text: [{text: "Line 1\nLine 2\nLine 3", options: { color: "0088cc", bullet: { type: "number" } } }] });

This will produce the desired result for multi text lines where there are no spaces, as in the provided example.

If you have spaces in the text lines, then you get a very different result.

Try the above snippet with "Line1\nLine2\nLine3", then with "Line 1\nLine 2\nLine 3".

**Comment by abhishekpani** [comment]
Its working with "Line1\nLine2\nLine3". But how can we do same for "Line 1\nLine 2\nLine 3"?

**Comment by willsgh** [comment]
Hi Abhishekpani,

Looks like there is a bug in the bullet option that affects text lines that have spaces. The multi-line rendering works with text containing spaces without the bullet option.

The solution for going around this depends on how you are generating and sending the content to pptxgenjs.

My content comes from a database, so what I did was instead of using the bullet option I sent the data from my database with unicode bullets already concatenated to the text.

Hope this helps.

cheers

**Comment by willsgh** [comment]
![Screenshot 2022-03-29 at 8 38 21 PM](https://user-images.githubusercontent.com/6756113/160703150-d4e6a90b-cf47-4273-92bd-a1012adf408f.png)

**Comment by abhishekpani** [comment]
Thank you @willsgh.

Unicode bullets appending to string worked for me.
