### ISSUE TITLE
WYSIWYG Editor or Playground

### ISSUE THREAD

**Issue by santi-git** [gitbrent/PptxGenJS#109]
Right now it's pretty hard to build a complex presentation given the validation cycle is long, you have to save and watch the changes.
It would be a great improvement in usability if there was a playground like the one in [PDFMake's Playground](http://pdfmake.org/playground.html) and it could be achieved by saving the PPT on user key up, or whenever user hits save, and then embedding a Google Slide's iframe.

**Comment by gitbrent** [comment]
Hi @santi-git ,

The PDFMake playground has a really nice interface.

Since the PptxGenJS library produces XML, I don't see how to easily translate that to HTML and then keep a `canvas` or `div` element populated.  That's basically what the PowerPoint Online engine does.

If you can find a way to make something like this work, that'd be super cool.
