### ISSUE TITLE
Special character encoding

### ISSUE THREAD

**Issue by ane1990** [gitbrent/PptxGenJS#116]
Hello,

i'm trying to insert unicode characters '©'  and 'é ' in a slide with addText('text', {options}). 
The slides was created with  those characters replaced with the 'missing' symbol '�'.

example: 
        // footer
        slide.addText('XXX © 2017. Uso riservato. Non diffondere né copiare.', { x: 0.39, y: 5.38, font_size: 6, font_face: slideFont });
then the result is : XXX � 2017. Uso riservato. Non diffondere n� copiare.

There are any options configuration that specify string encoding to solve the problem ?

**Comment by gitbrent** [comment]
Hi @ane1990,

I'm not able to reproduce this problem.  The `examples/pptxgenjs-demo.html` file includes other languages and seems to work for everyone, so i'm unsure what the issue is.

What version of PowerPoint and what version of PptxGenJs are you using?

```javascript
slide.addText(
  [
    { text:'©',   options:{ font_size:24, color:'99ABCC' } },
    { text:'é',   options:{ font_size:36, color:'FFFF00' } },
    { text:'你好', options:{ font_size:48, color:'0088CC' } }
  ],
  { x:1.5, y:1.5, w:6, h:2, margin:0.1, fill:'232323' }
);
```

![screen shot 2017-07-17 at 22 54 49](https://user-images.githubusercontent.com/7218970/28300173-51353c82-6b43-11e7-9d5b-73862cce6c67.png)

**Comment by ane1990** [comment]
I'm using PptGenJS v1.5.0 and  Powerpoint 2016, the broken characters are also in the underlay slide xml.

I developed the js with Visual Studio 2013 and deployed on Sharepoint 2013, both editor and deployed file seems to be  utf8 encoded ). 

I solve the problem excluding those characters in static string :

// footer
        var copyChar = unescape('%A9');
        var eAcuteChar = unescape('%E9');
        slide.addText('XXX ' + copyChar + ' 2017. Uso riservato. Non diffondere n' + eAcuteChar + ' copiare.', { x: 0.39, y: 5.38, font_size: 6, font_face: slideFont });
