### ISSUE TITLE
Specify where to save ?

### ISSUE THREAD

**Issue by pierpieandthe** [gitbrent/PptxGenJS#168]
Hello,
First of all, you made a great job, PptGenJS is quite impressive !

Is there a way to say directly by command line where to save - something that would look like
pptx.save('Demo-Simple', './SaveInThisRepository') ?

If no (I haven't seen it), where do do you specify where the file is saved ? (I had look to doExportPresentation and writeFileToBrowser function in pptxgen.js file but I can't clearly identify how the path where to save is identified)

Thank you

**Comment by gitbrent** [comment]
Hi @pierpieandthe ,

There's no parameter specifying where to save the file to, however, check out the `examples/nodejs-demo.js` file and you'll see that the file is created in the PWD.  It'd be trivial to use `fs` to move it to any filesystem location once it's created.

**Comment by JamesRobert20** [comment]
Hi regarding the same issue, I was trying to see where I could modify your code to make it download the powerpoint into the directory I wish, instead of using fs to move the file from Downloads to the directory but no luck so far, do you have an idea how. Would be really important to have that feature

Thanks
