### ISSUE TITLE
cannot read property 'opts' of null

### ISSUE THREAD

**Issue by ninas880025** [gitbrent/PptxGenJS#17]
Hello

I have this issue:
![image 058](https://cloud.githubusercontent.com/assets/13866745/21307638/662b767e-c611-11e6-8bc3-ae27efbafc15.png)

it sometimes can't load the image I put in my local directory.(sometimes it works)
this is my code: pptx.addNewSlide().addImage({x:1.75, y:1.81, w:7.2, h:2.31,path:'datalog/assets/img/KYEC.png'});

**Comment by ninas880025** [comment]
more details abt image issue
![image 059](https://cloud.githubusercontent.com/assets/13866745/21307792/fbabb344-c611-11e6-892b-f30394c84e4b.png)

**Comment by gitbrent** [comment]
Hi,

Thanks for reporting this.

What version are you using?

Also note that if you are running this on your local browser, you'll need to enable local file access (e.g.: Chrome flag "--allow-file-access-from-files")

**Comment by ninas880025** [comment]
Hi,

My version is 1.1.2




2016-12-20 12:10 GMT+08:00 Brent Ely <notifications@github.com>:

**Comment by gitbrent** [comment]
Thanks.

The images not loading is related to local file access.  Howevee, the uncaught error you helpfully screen-grabbed is in the table building loop.

Could you show me the code you're using to specify a table by any chance?

**Comment by rikvdk** [comment]
I have the same problem with an image not being loaded:

![image_not_loaded](https://cloud.githubusercontent.com/assets/1284166/21421682/779c2ce4-c834-11e6-9987-99bf1140a316.png)

The problem could be the response from the server: 304 Not Modified. What happens is chrome sends the request with the header:

- If-Modified-Since:[date]

The server in response says it hasn't changed with a 304 status code. I guess this isn't handled in the PptxGenJS code which makes it fail later on when the image is used.

**Comment by gitbrent** [comment]
Thanks again for all the information.

I've updated the library with fixes that should address all of the issues you've encountered.  Please try again using the most recent `pptxgen.js` file.

**Comment by ninas880025** [comment]
thanks for solving our issue. I had re-npm install pptxgenjs and allowed local file access but the same error message appeared again.

**Comment by ninas880025** [comment]
this is my code for image:
![image 062](https://cloud.githubusercontent.com/assets/13866745/21446470/65fca572-c901-11e6-9c72-5a651a4f67d4.png)

this is how I define my table header using opts:
![image 063](https://cloud.githubusercontent.com/assets/13866745/21446485/8a7afa2a-c901-11e6-9a1c-25791aeb9ad0.png)
I loop through headerName, making the header has filling color

**Comment by gitbrent** [comment]
Oh, i should have asked how you were obtaining the library...  I hadn't pushed an update to NPM yet, I had just staged the package file, so your update did not pull in any new files.

I've updated the NPM release to 1.1.3 now, so please update and let me know if these issues are now fixed.

**Comment by ninas880025** [comment]
Hello, 

I npm install the new version(1.1.3) and allowed local file access in chrome bur the error is the same:
![image 065](https://cloud.githubusercontent.com/assets/13866745/21474490/fcac631c-cb5a-11e6-8e3b-09c85b55f944.png)

could you help with this? thanks!

**Comment by gitbrent** [comment]
Okay, version 1.1.3-2 has been pushed to npm.  Try that out and let me know.

- The image onLoad error message now provides a complete (clickable from Chrome dev window) link to the image that couldn't be loaded for easy verification.
- The second error was due to the empty string and/or null being the cell's value and/or text value and that issue is fixed now.

**Comment by ninas880025** [comment]
Hi, both problems has been solved. thank you very much!

**Comment by gitbrent** [comment]
Good to hear!

Thanks for reporting these issues and working through them.
