### ISSUE TITLE
Save callback is not called by client-browser when there are images to encode

### ISSUE THREAD

**Issue by Malangs** [gitbrent/PptxGenJS#187]
I've been upgrading from an older version to the latest release and encountered the following bug: If I embed an image in the presentation, the callback in `save` does not work. I've only tested it in the browser but I suspect the same behavior occurs in _Node.js_. After reverse engineering the code a bit I think I found the problem. If there is an image to encode, the last asynchronous image convert function calls `doExportPresentation`, otherwise the latter will be called by `save` directly. However, the image converting functions (`encodeImageRelations` --> `convertImgToDataURLviaCanvas` --> `callbackImgToDataURLDone`) do not propagate the callback. Hope that helps.

**Comment by gitbrent** [comment]
Hi @Malangs ,

Thanks for reporting this and for taking the time to identify the root cause.  As you discovered the callback was not being propagated. 

Callbacks were working on Node.js (using a callback is the default for the node demo), I had just neglected to test this functionality in browsers for awhile.

**Comment by Malangs** [comment]
Hi @gitbrent, thanks for the fix! Glad I could help.
