### ISSUE TITLE
Default text size in empty cells making row height too big

### ISSUE THREAD

**Issue by mreilaender** [gitbrent/PptxGenJS#193]
When a cell in a row doesn't contain text it's default text size is 18. This makes the height of the row too big (see below)
![row_height_too_big](https://user-images.githubusercontent.com/6803839/30595360-446f6690-9d51-11e7-9419-42b27a1c33c1.png)

Compairision when every cell contains text
![row_height_ok](https://user-images.githubusercontent.com/6803839/30595624-f8f6e7d2-9d51-11e7-891c-1edbcc63c697.png)

I know its a duplicate (#20) but no solution was provided

**Comment by gitbrent** [comment]
Hi @mreilaender ,

Thanks for reporting this!  The fix for Issue #20 got clobbered somewhere along the way to the current version of the text parsing engine and was not working correctly.

Empty cells are now formatted correctly in the current codebase:

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

slide.addTable(
	['using null','2','3','4','5','',null,undefined],
	{ x:0.5, y:0.5, w:9 },
	{ fill:'F1F2F3', font_size:12, color:'363636', border:{pt:'1', color:'BBCCDD'} }
);

pptx.save('PptxGenJS-Issue193');
```
![screen shot 2017-09-20 at 22 39 48](https://user-images.githubusercontent.com/7218970/30678762-3863c4b8-9e5a-11e7-8325-5c802871de5c.png)
