### ISSUE TITLE
addSlidesForTable splits single table row across two slides

### ISSUE THREAD

**Issue by sungkimns** [gitbrent/PptxGenJS#196]
When the table height is not specified to 100% the table is split across multiple slides, but the table is split in the middle of a row instead of between two rows as would be expected.

**Comment by gitbrent** [comment]
Hi @sungkimns ,

This is not enough information on which to create an Issue.

You'll need to provide some sample code and some screencaps showing what your inputs are and what you're looking for.

**Comment by sungkimns** [comment]
Here's a capture of the original table
![image](https://user-images.githubusercontent.com/21201103/30709260-405d375e-9ec7-11e7-844d-bfbbb4df82af.png)

And here's what it looks in the power point after running it through the addSliderForTable function. The 'Cumulative Investments' row is split between slides and is now two separate rows. I've created a separate issue for the background color on the header not rendering correctly.
![image](https://user-images.githubusercontent.com/21201103/30709314-699962b4-9ec7-11e7-9bbf-639faa5c8222.png)
![image](https://user-images.githubusercontent.com/21201103/30709328-7610adc2-9ec7-11e7-857d-e9477649fcb5.png)

The code to generate the slide.
![image](https://user-images.githubusercontent.com/21201103/30709483-f7191a8a-9ec7-11e7-8fa8-75882f2679b7.png)

**Comment by gitbrent** [comment]
Thanks for the information.

Aside from the table head cells not correctly picking up their background color (Issue #195), the reason "Cumulative Investments" ended up across these 2 rows was just the luck of the draw.

If that cell has less text (just "Cumulative") and the next cell has a larger amount of text ($100,000,000,000,000), then the second cell would have overflowed and the header cell would not.

It's no so much that the cell was "split" across rows as it is the fact that some cells in a row have text that overlfows while some do not...

In this case, it looks like it'd be easy to just "pull" that whole row down instead of even splitting it, but it doesn't always work out that way with other test cases - the project demos include long blocks of text/taller cells, and you would not want to start pushing those down to the next Slide.

It's an interesting coding problem for sure!
