### ISSUE TITLE
addImage() - Support for animated GIFs?

### ISSUE THREAD

**Issue by shashank2104** [gitbrent/PptxGenJS#22]
Hi, 

Thank you for the wonderful project. It is indeed very useful. 
Issue: I tried adding a **gif** image to the ppt, it works fine but the animation doesn't. It gets embedded as an image and not a movie. (just copying a gif into a ppt embeds itself as a movie)

Do you think that feature is already available and I'm doing it wrong or is it something that still needs to be implemented? 

Can you try that and let me know if it works? 

Thanks.

**Comment by gitbrent** [comment]
Thanks for the feedback!

I never tried using animated GIFs in a Presentation... let me look into how the images are being encoded/included and see what can be done to support this.

**Comment by shashank2104** [comment]
Sure! Thank you.

**Comment by shashank2104** [comment]
Hey @gitbrent , 

Any updates on this issue? 
Do you think this feature can be added? 

Thanks.

**Comment by gitbrent** [comment]
Good news!  This can be done... but in only 1 of 2 ways.

If you use Node.js or pre-encode the gif and pass it to `addImage()` using the data option, it'll render as an animated gif in PPT.

Images added with path: cannot be encoded into GIFs because the method for doing so isn't supported yet (even in Chrome).

Version 1.1.6 will be out soon and will provide this functionality.

**Comment by shashank2104** [comment]
Hey Brent, 

I did test it using the demo file and it works absolutely fine. Thanks a lot.
