### ISSUE TITLE
Table-to-Slides issue

### ISSUE THREAD

**Issue by svaak** [gitbrent/PptxGenJS#284]
I am having an issue when trying to generate a html table to PowerPoint using the Table-to-Slides feature. The table appears fine on my SharePoint site but when I open the generated PowerPoint it shows a lot of extra columns. Below is my basic HTML test table and attached is a screenshot of the PowerPoint generated. The problem seems to happen only if I include colspan.
**<table class="tg" id="tableId2">
<tr>
<th class="tg-header">First Name</th>
<th class="tg-header">Last Name</th>
<th class="tg-header">Count</th>
<th class="tg-header">TestColumn1</th>
<th class="tg-header" colspan="2">TestColumn2</th>
<th class="tg-header">TestColumn3</th>
</tr>
<tr>
<td>Jill</td>
<td>Smith</td>
<td>50</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
</tr>
<tr>
<td>Eve</td>
<td>Jackson</td>
<td>94</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</table>**

![issueimg](https://user-images.githubusercontent.com/36235053/35925700-54a7746c-0c1e-11e8-8618-f6561f15de7c.PNG)
![issueimg2](https://user-images.githubusercontent.com/36235053/35925701-54cf343e-0c1e-11e8-9181-1ab51bf14818.PNG)

I tried editing the pptxgenjs-demo.html file by adding in the colspan attribute for the Table to slides table and the same thing happens there as well when the PowerPoint is generated.

**Comment by gitbrent** [comment]
Hi @svaak,

Thanks for letting me know about this.  The colspan logic broke a while back and i had no test for it, hence the bug.

Issue is now fixed in the main branch and i've added a new demo section for colspans

![screen shot 2018-02-18 at 23 11 22](https://user-images.githubusercontent.com/7218970/36363266-4a627196-1501-11e8-8f47-493cffe1330d.png)

![screen shot 2018-02-18 at 23 11 52](https://user-images.githubusercontent.com/7218970/36363268-4d765938-1501-11e8-8375-dc1e69e17ae6.png)

**Comment by svaak** [comment]
Thanks Brent !!
