### ISSUE TITLE
Formatting rules do not apply to string with '\n'

### ISSUE THREAD

**Issue by itskun** [gitbrent/PptxGenJS#34]
Formatting rules are ignored after the symbol '\n', e.g:
`slide4.addText('first paragraph\nsecond paragraph\nthird paragraph', { x: 0.0, y: '50%', valign: 'middle', align: 'center', color: '000000', font_face: 'Times New Roman', font_size: 16, isTextBox:true});`
It looks like:
![image](https://cloud.githubusercontent.com/assets/9961535/22692871/f3814c08-ed51-11e6-9acc-5448b4f9c9c3.png)

**Comment by gitbrent** [comment]
Hi @itskun,

Thanks for reporting this issue!

There was actually an underlying issue here with text run formatting within paragraphs that needed fixing.

Lastly, I've updated the `README` and `examples/pptxgenjs-demo.html` page with an code showing how to format down to the word/line level, so you could align/format each of your 3 lines above differently.

```javascript
slide.addText(
 [
  { text:'1st line', options:{ font_size:24, font_face:'Courier New', color:'99ABCC', align:'r', breakLine:true } },
  { text:'2nd line', options:{ font_size:36, font_face:'Arial',       color:'FFFF00', align:'c', breakLine:true } },
  { text:'3rd line', options:{ font_size:48, font_face:'Verdana',     color:'0088CC', align:'l' } }
 ],
  { x:0.5, y:1.1, w:6, h:3, margin:0.1, fill:'232323' }
);
```

![issue34fix](https://cloud.githubusercontent.com/assets/7218970/22812615/5d2a6184-ef0b-11e6-86b3-682ab1fad077.png)  

![issue34exfix](https://cloud.githubusercontent.com/assets/7218970/22812666/b02216fc-ef0b-11e6-81f8-1152052c01cf.png)
