### ISSUE TITLE
addText with hyperlink and addImage cannot co-exist in a slide?

### ISSUE THREAD

**Issue by rickykoh** [gitbrent/PptxGenJS#465]
Hello Team,

Not sure if this is a bug or PowerPoint's limitation but I have tried and tested adding both hyperlink text and image in a same slide using addText and addImage respectively, which will cause an error as below when trying to open the downloaded ppt:

![error](https://user-images.githubusercontent.com/17489896/50539644-8257e180-0bbe-11e9-8937-62de79b466f9.JPG)

However, the PowerPoint shows no error if the slide only exists either hyperlink text or image.

Thanks!

**Comment by gitbrent** [comment]
Please provide the PowerPoint version, the PptxGenJS version, and the code being used.

**Comment by rickykoh** [comment]
I have tested on PowerPoint version 2010 and 2016. 
PptxGenJS version used is 2.4.0

Code used is as below: 
`var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

var position = {
            x: 0.4,
            y: 1.0
        };
        
        var rows = [];
        for (var m = 0; m < 4; m++) {
            rows.push({
                text: "Text " + m,
                options: headerOption
            });
        }
        
        slide.addText(rows, position);
        slide.addImage({ path:'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg', x:1.5, y:1, w:6, h:4 });`

**Comment by stephanielsx** [comment]
Hi,

Any updates?

Thanks.

**Comment by rickykoh** [comment]
Hi,

Any updates?

Thanks.

**Comment by rickykoh** [comment]
Hi, any exact date for the completion of solving this bug?

**Comment by ReimaFrgos** [comment]
This issue seems to be at line 2200 in the createHyperlinkRels function

`var intRels = 1;`
should be
`var intRels = 0;`

The increased start count is causing the hyperlink rID object to be a duplicate if any of image, chart, audio, or video are also on the page.

I don't have time to submit a PR right now, but should be able to do so this week.

I have tested the change using multiple hyperlinks, images, and charts all in the same page using the code below.

`var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

var position = { x: 0.4, y: 1.0 };
var position2 = { x: 1.4, y: 2.0 };
var headerOption = {
            bullet: false,
            font_size: 12,
            hyperlink:{ slide:2 }
        };
var headerOption2 = {
            bullet: false,
            font_size: 12,
            hyperlink:{ slide:4 }
        };
        
var rows = [];
for (var m = 0; m < 4; m++) {
  rows.push({
     text: "Text " + m,
     options: headerOption
  });
}

var rows2 = [];
for (var m = 0; m < 4; m++) {
  rows.push({
     text: "Text " + m,
     options: headerOption2
  });
}
        
slide.addText(rows, position);
slide.addImage({ path:'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg', x:1.5, y:1, w:6, h:4 });
var dataChartRadar = [
    {
        name  : 'Region 1',
        labels: ['May', 'June', 'July', 'August', 'September'],
        values: [26, 53, 100, 75, 41]
    }
];
slide.addChart( pptx.charts.RADAR, dataChartRadar, { x:0.5, y:0.6, w:6.0, h:4, radarStyle:'standard' } );
slide.addImage({ path:'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg', x:2.5, y:2, w:6, h:4 });
slide.addText(rows2, position2);




pptx.save('PptxGenJS-Sandbox_'+getTimestamp());`

**Comment by gitbrent** [comment]
Issue has been resolved. Target release `2.5.0`
