### ISSUE TITLE
TRBL margin for text object

### ISSUE THREAD

**Issue by dtyagunov** [gitbrent/PptxGenJS#551]
Is there a way to set only, for instance, a top margin for text object?

**Comment by SvistunovYuriy** [comment]
👍 same

**Comment by ReimaFrgos** [comment]
Yes, you can pass in an array for the margin.
`slide.addText('Hello World',  { x:0.5, y:0.7, w:6, h:6, color:'0000FF', fontSize:18, margin:[100,100,100,100]});`

Currently it's configured as LRBT rather than TRBL so to set just the top you would use:
`margin:[0,0,0,100]`

@gitbrent it would be a breaking change  if anyone is using it (although it's currently undocumented), but maybe this could be converted to be TRBL style in 3.0 to consistent with table margins? 

Code kicks in at Line: 1038 in current dist.

**Comment by gitbrent** [comment]
Fixed in v3.0
