### ISSUE TITLE
How to add multiple shapes in "HTML-to-PowerPoint" slide

### ISSUE THREAD

**Issue by tubean** [gitbrent/PptxGenJS#561]
Hi team,
I am using HTML-to-PowerPoint Feature to build a new slide from my HTML code. But after converting, I wanna add some shapes to this slide. How can I do it?
Thank you.

**Comment by gitbrent** [comment]
Hi @tubean 

There is no way to add any content to a Presentation once created via the HTML-to-PPT function - it's designed to be a single pass process.

Can you utilize a Master Slide to add content to each slide instead of post-processing it?

See the [online demo](https://gitbrent.github.io/PptxGenJS/demo/#tab2) for a working example.
