### ISSUE TITLE
"dataLabelFontBold" option not working as expected.

### ISSUE THREAD

**Issue by belall-shaikh** [gitbrent/PptxGenJS#662]
Hi, the "dataLabelFontBold" option of chart is not working. 
Please check below fiddle: 

https://jsfiddle.net/skbelal/q3k6wazf/13/

**Comment by gitbrent** [comment]
Hi @skbelalmd 

When i run the fiddle, I get the following which shows bold labels at the bottom. Are you seeing or expecting something different?

<img width="1111" alt="Screen Shot 2020-02-03 at 21 30 46" src="https://user-images.githubusercontent.com/7218970/73711472-9842aa80-46cc-11ea-9bc7-18d151eb3661.png">

**Comment by skbelalmd** [comment]
Hi,
I too get the same result.

![image](https://user-images.githubusercontent.com/15244653/73749272-05b01300-4781-11ea-8498-45a8d59e55ad.png)

The bold labels at the bottom is because of "catAxisLabelFontBold" attribute set as true.
I am referencing here the data-labels (values of the columns inside it). It is not getting bold as per the  attribute "dataLabelFontBold"

**Comment by gitbrent** [comment]
Fixed via Pull #938
