### ISSUE TITLE
Setting colW when colSpan is used

### ISSUE THREAD

**Issue by psubrownie** [gitbrent/PptxGenJS#729]
Reopening #461 
using w[idth] no longer fixes the colspan issue in version 3.x
2.6: https://jsfiddle.net/psubrownie/dun98e4t
3.1.1: https://jsfiddle.net/psubrownie/rcgkea8t/

**Comment by gitbrent** [comment]
@psubrownie 

The code in 3.x is more complex about handling these scenarios. If you would've used 2 cols for your first row, the code would have done what you expected as you passed two values for colW and had 2 cells.  Since the column count didn't match, the code preferred the `w` value.

The docs should say to use either one or the other, not both `colW` and `w` values.

**Comment by mlvaughn10** [comment]
Hey @gitbrent, so if I'm understanding this correctly, there's no way to have the first row span several columns AND have the subsequent rows have non-equal column widths. When you use colspan on the first column, you have to specify w[idth] and then can't also specify colW - any plans to update this feature?

@psubrownie - have you made any suitable adjustments to your needs that has worked well in the. interim?

**Comment by psubrownie** [comment]
@mlvaughn10  I think I ended up making a new table and positioning it under the first one

**Comment by mlvaughn10** [comment]
Thanks for the idea @psubrownie. I had thought of a couple other ideas, but I kind of like that one.

**Comment by gitbrent** [comment]
Is there a breaking test case for this?
