### ISSUE TITLE
Stacked bar chart: how to add sum of values out of the bar end?

### ISSUE THREAD

**Issue by smurfs2549** [gitbrent/PptxGenJS#844]
Many thanks for this package.
Is it possible to add sum of values out end of the bar? 
![image](https://user-images.githubusercontent.com/8286468/93188684-dc724f00-f773-11ea-85f4-51122ab6cf27.png)

**Comment by gitbrent** [comment]
Can this be done in PowerPoint? Can you provide a screencap of the options?

**Comment by ReimaFrgos** [comment]
This is not a valid data label for this chart type in PowerPoint. Two options you might want to try depending on your needs.
1. If you know/force the scale of the chart, you could calculate the position of placing a text box on top of the chart at the relevant point that contains the total. This would look correct, but if you needed to edit the chart after being produced, the values wouldn't auto update. OR;
2. If you can change to a column chart instead of a bar chart, you could use a column + line chart combo. Make the line chart equal to the SUM value, and then add the data labels. Hide the line by effectively making it invisible with a 0 width.
