### ISSUE TITLE
Unhandled promise rejection TypeError: Unable to set property 'interception' of undefined or null reference

### ISSUE THREAD

**Issue by spncs** [gitbrent/PptxGenJS#933]
Hello everybody,

I'm trying to create a .pptx on a SP2016 system. In this case IE11 is used, a test using Chrome was successful, as soon as the script is executed on IE11, the console outputs the error message mentioned at the title. Can someone tell me where the problem is? Unfortunately I couldn't find an existing post for the error message, so I'm going to open a new one here. Many Thanks. 

```
<html>
    <head>
		<script language="javascript" type="text/javascript" src="/SiteAssets/jquery.min.js"></script>
		<script language="javascript" type="text/javascript" src="/SiteAssets/pptxgen.bundle.js"></script>
		<script type="text/javascript">
            function CreateReport()
                {
                    console.log("CreateReport Start");
					var pptx = new PptxGenJS();
					var slide = pptx.addSlide();

					slide.addText("BONJOUR - CIAO - GUTEN TAG - HELLO - HOLA - NAMASTE - 你好", {
						x: 0,
						y: 1,
						w: "100%",
						h: 2,
						align: "center",
						color: "0088CC",
						fill: "F1F1F1",
						fontSize: 24,
					});

					pptx.writeFile({ fileName: "PptxGenJS-Demo.pptx" });
                    console.log("CreateReport End");
                }
		</script>
    </head>
</html>
```

Console Error:
Unhandled promise rejection TypeError: Unable to set property 'interception' of undefined or null reference
   "Unhandled promise rejection"
   {
      [functions]: ,
      description: "Unable to set property 'interception' of undefined or null reference",
      message: "Unable to set property 'interception' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to set property 'interception' of undefined or null reference
   at writeFileToBrowser (.../SiteAssets/pptxgen.bundle.js:2:334130)
   at Anonymous function (.../SiteAssets/pptxgen.bundle.js:2:379440)
   at e (.../SiteAssets/pptxgen.bundle.js:2:158413)
   at Anonymous function (.../SiteAssets/pptxgen.bundle.js:2:158560)
   at t (.../SiteAssets/pptxgen.bundle.js:2:119709)"
   }

**Comment by gitbrent** [comment]
This stems from a call in the write method to address [this SharePoint issue](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/hyperlinking) that prevents downloads from being processed.

https://github.com/gitbrent/PptxGenJS/blob/0a80bab6f556d8d475d1402ca1fcb9116490fa5f/src/pptxgen.ts#L421

Since this line is called for all users, i'm suspecting this is an IE11 only issue.

If that's the case, we will not be patching the code as IE11 has been dropped from support starting with the very next release v.3.6.0

IE11 has been desupported on Teams and will be dropped entirely by MS in the summer, so asking your users to switch to a modern borwser is all we can suggest.
